### ISSUE TITLE
[REFACTOR] 코드리뷰 반영

### ISSUE THREAD

**Issue by j2h30728** [j2h30728/disney#3]
## TODO

#1 , #2  에 대한 코드리뷰 반영 계획

- [ ] Loader 사용 적용
- [x] fetch 다른 방식 고안
- [x] error boundary 설정
- [x] 식별자 네이밍 변경 : handle-prefix
